backend:
  name: github
  repo: vubipvu/web-carton # Đúng tên repo của Vũ
  branch: main
  base_url: https://khanhbox-auth.vercel.app
  auth_endpoint: api/index

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Sản phẩm KhanhBox"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tên sản phẩm", name: "title", widget: "string" }
      - { label: "Giá", name: "price", widget: "number" }
      - { label: "Mô tả", name: "body", widget: "markdown" }
      - { label: "Hình ảnh", name: "image", widget: "image" }